Format `ElasticRecord::ConnectionError` messages as JSON
data-axle/elastic_record pull request #166
Opened 2023-01-07 05:22 UTC by matthinea

### Problem

When an `ElasticRecord::ConnectionError` gets raised, its error message is one of two things:
* a string representation of a Ruby hash
* a string representation of a Ruby hash, with some additional non-hash text appended to it

This is inconvenient if a developer wants to dig around in the error message, which is a likely scenario seeing as this error covers lots of Elasticsearch query shard execptions and parse exceptions.

### Solution

* Raise `ConnectionError` in a consistent way
* Pass the raw JSON to the error as its message
* Concatenate the payload (when present) to the error message such that it's still valid JSON

2023-01-09 16:56 UTC, betesh-at-data-axle requested changes
Should we make this a breaking change by requiring `payload` in ConnectionError's initializer?  That would force clients that are raising it directly (if any are) to also include the payload in the error message.

2023-01-10 01:12 UTC, matthinea commented
@betesh-at-data-axle sometimes there isn't a payload, which would force users to pass `nil`. So, I don't think it's really needed

2023-01-10 06:08 UTC, betesh-at-data-axle commented on lib/elastic_record/errors.rb
> +        }
If one is parse-able and the other isn't, no point in not parsing the one that we can parse:

```suggestion
        payload = if json_payload
          begin
            JSON.parse(json_payload)
          rescue JSON::ParserError
            json_payload
          end
        else
          nil
        end
        
        begin
          JSON.parse(json_error).merge(payload:)
        rescue JSON::ParserError
          { error: json_error, payload: }
        end
```

2023-01-10 09:44 UTC, matthinea commented on lib/elastic_record/errors.rb
> +        payload = { request_payload:        parse_or_return(json_payload) }
If payload isn't provided, this will just return `nil`; so, no need to set a default.

2023-01-10 16:18 UTC, betesh-at-data-axle approved these changes
Approved with one request

2023-01-10 17:06 UTC, merged